// ---------------------------------------------------------------------------
// /sitemap.xml — autogenerated from DB on every request (cached by Next at
// the `getPaquetesPublicados` / `getRegionesPublicas` layer).
//
// Three groups:
//   1. Static public routes (home, about, contact, faq, terms, cotizar, etc.)
//   2. All public Regions (/destinos/<slug>)
//   3. All published Paquetes (/destinos/<region-slug>/<paquete-slug>)
//
// `lastModified` comes from the entity's `updatedAt` so search engines only
// re-crawl what actually changed.
//
// Base URL is read from APP_URL env (or NEXTAUTH_URL as fallback). At local
// dev defaults to http://localhost:3000.
// ---------------------------------------------------------------------------

import type { MetadataRoute } from "next";
import { prisma } from "@/lib/db";
import { BRAND_ID } from "@/lib/brand";

export const dynamic = "force-dynamic";
export const revalidate = 3600; // 1h is plenty for a brochure site

function getBaseUrl(): string {
  const raw =
    process.env.APP_URL ??
    process.env.NEXTAUTH_URL ??
    "http://localhost:3000";
  return raw.replace(/\/+$/, "");
}

const STATIC_ROUTES: Array<{
  path: string;
  changeFrequency: MetadataRoute.Sitemap[number]["changeFrequency"];
  priority: number;
}> = [
  { path: "/", changeFrequency: "weekly", priority: 1.0 },
  { path: "/destinos", changeFrequency: "weekly", priority: 0.9 },
  { path: "/destinos/todos", changeFrequency: "weekly", priority: 0.85 },
  { path: "/about", changeFrequency: "monthly", priority: 0.6 },
  { path: "/contact", changeFrequency: "monthly", priority: 0.7 },
  { path: "/corporativo", changeFrequency: "monthly", priority: 0.7 },
  { path: "/cotizar", changeFrequency: "monthly", priority: 0.8 },
  { path: "/faq", changeFrequency: "monthly", priority: 0.5 },
  { path: "/terms", changeFrequency: "yearly", priority: 0.3 },
  { path: "/work-with-us", changeFrequency: "monthly", priority: 0.4 },
];

export default async function sitemap(): Promise<MetadataRoute.Sitemap> {
  const base = getBaseUrl();
  const now = new Date();

  // Try DB; if it errors at build time (e.g. missing DATABASE_URL during a
  // dry-run), still return the static set so the route never 500s.
  let regions: Array<{ slug: string; updatedAt: Date }> = [];
  let paquetes: Array<{
    slug: string | null;
    updatedAt: Date;
    region: { slug: string } | null;
  }> = [];
  let tags: Array<{ slug: string; updatedAt: Date }> = [];

  try {
    regions = await prisma.region.findMany({
      where: { brandId: BRAND_ID },
      select: { slug: true, updatedAt: true },
    });
  } catch (err) {
    console.warn("[sitemap] regions query failed:", err);
  }

  try {
    const rows = await prisma.paquete.findMany({
      where: {
        publicado: true,
        deletedAt: null,
        brandId: BRAND_ID,
        slug: { not: null },
      },
      select: {
        slug: true,
        updatedAt: true,
        destinos: {
          orderBy: { orden: "asc" },
          take: 1,
          include: {
            ciudad: { include: { pais: { include: { region: true } } } },
          },
        },
      },
    });
    paquetes = rows.map((p) => ({
      slug: p.slug,
      updatedAt: p.updatedAt,
      region: p.destinos[0]?.ciudad?.pais?.region
        ? { slug: p.destinos[0].ciudad.pais.region.slug }
        : null,
    }));
  } catch (err) {
    console.warn("[sitemap] paquetes query failed:", err);
  }

  // Etiquetas "activas": las que tienen al menos un paquete publicado, no
  // borrado y vigente (misma vigencia que usa /tag/[slug] al listar). Una
  // etiqueta sin paquetes vivos renderiza una landing vacía, así que no va al
  // sitemap. `hoy` en formato local YYYY-MM-DD para comparar contra
  // validezHasta (ver vigenciaActivaWhere en public-data).
  try {
    const hoy = new Date().toLocaleDateString("en-CA");
    const rows = await prisma.etiqueta.findMany({
      where: {
        brandId: BRAND_ID,
        paquetes: {
          some: {
            paquete: {
              publicado: true,
              deletedAt: null,
              brandId: BRAND_ID,
              OR: [{ validezHasta: null }, { validezHasta: { gte: hoy } }],
            },
          },
        },
      },
      select: { slug: true, updatedAt: true },
    });
    tags = rows;
  } catch (err) {
    console.warn("[sitemap] etiquetas query failed:", err);
  }

  const staticEntries: MetadataRoute.Sitemap = STATIC_ROUTES.map((r) => ({
    url: `${base}${r.path}`,
    lastModified: now,
    changeFrequency: r.changeFrequency,
    priority: r.priority,
  }));

  const regionEntries: MetadataRoute.Sitemap = regions.map((r) => ({
    url: `${base}/destinos/${r.slug}`,
    lastModified: r.updatedAt,
    changeFrequency: "weekly",
    priority: 0.8,
  }));

  const paqueteEntries: MetadataRoute.Sitemap = paquetes
    .filter((p): p is typeof p & { slug: string; region: { slug: string } } =>
      Boolean(p.slug && p.region),
    )
    .map((p) => ({
      url: `${base}/destinos/${p.region.slug}/${p.slug}`,
      lastModified: p.updatedAt,
      changeFrequency: "weekly",
      priority: 0.7,
    }));

  const tagEntries: MetadataRoute.Sitemap = tags.map((t) => ({
    url: `${base}/tag/${t.slug}`,
    lastModified: t.updatedAt,
    changeFrequency: "weekly",
    priority: 0.6,
  }));

  return [
    ...staticEntries,
    ...regionEntries,
    ...paqueteEntries,
    ...tagEntries,
  ];
}
