/**
 * import-hotels-from-sheets.ts — Reads the client's public Google Sheets
 * (one doc per country, one tab per city) and produces an import plan for
 * the Alojamiento table.
 *
 * Modes:
 *   (no flag)    dry-run. Prints breakdown + anomalies, no DB writes.
 *   --confirm    creates missing Ciudades and inserts new Alojamiento rows
 *                in parallel to existing hotels. Does NOT delete the 274
 *                existing hotels (that happens in migrate-hotels.ts).
 *
 * Optional:
 *   --snapshot-output=<path>   writes the parsed hotel plan as JSON
 *
 * The script never touches Region / Pais / Ciudad beyond creating missing
 * cities from the Sheets.
 */

import { PrismaClient } from '@prisma/client';
import { writeFileSync } from 'fs';
import { generateSequentialId } from '../src/lib/sequential-id';

const prisma = new PrismaClient();
const BRAND_ID = 'brand-1';

// ---------------------------------------------------------------------------
// Sheet index — generated by exploring client's public docs (Apr 2026).
// Key: country name (must match Pais.nombre in DB). Value: doc ID + tab names.
// ---------------------------------------------------------------------------

type SheetSource = { docId: string; tabs: string[] };

const SHEET_SOURCES: Record<string, SheetSource> = {
  España: {
    docId: '1Lc77ULaQNOFh0jvu1WWuMLb3oJKNhRlfDH-8uO3mD-Y',
    tabs: ['MADRID', 'BARCELONA', 'IBIZA', 'PALMA DE MALLORCA'],
  },
  Italia: {
    docId: '1_OPPTw9g_m9MyMK-Syn3paBAD52Qk-GtFNPt0b1INbY',
    tabs: ['ROMA', 'FLORENCIA', 'MILAN', 'VENECIA'],
  },
  'Países Bajos': {
    docId: '1tXtWKwnIuFlR3jSgVgi0btgD7nOsqNhosq8hMKlnI6E',
    tabs: ['Amsterdam'],
  },
  'Reino Unido': {
    docId: '1Po21VyAcDvEIppBymlnILrwrNGiXXS0e9EYrC8LDQkg',
    tabs: ['LONDRES'],
  },
  Francia: {
    docId: '1kIv3SRG1j4zuzXzS5SpcXubtY0uOJQN1oEtEF8C2os8',
    tabs: ['PARÍS'],
  },
  Portugal: {
    docId: '1RfjnRzRSNfuystwjBpjTL5J9NJf1tFLd_HlofbcWnuc',
    tabs: ['LISBOA', 'OPORTO', 'ALBUFEIRA'],
  },
  'Estados Unidos': {
    docId: '17wJIMlMp30SbJWYRBNgpwIManOdRAZhz9pAugwaOeUI',
    tabs: ['NUEVA YORK', 'SAN FRANCISCO', 'LAS VEGAS', 'LOS ÁNGELES', 'ORLANDO', 'MIAMI'],
  },
  Argentina: {
    docId: '1AqGX_Awjdmc9iQGmD0KC4a8oLhB_PrwBgOKHBEMJ4SQ',
    tabs: [
      'BARILOCHE',
      'BUENOS AIRES',
      'CALAFATE',
      'MENDOZA',
      'SAN MARTIN DE LOS ANDES',
      'USHUAIA',
      'VILLA LA ANGOSTURA',
    ],
  },
  Brasil: {
    docId: '1MBSvp8d4oeAeZAaq3AZxEEr_4N-mc5yprcHswGBqOKs',
    tabs: [
      'ALL INCLUSIVE EN ALAGOAS',
      'ALL INCLUSIVE BAHIA',
      'ARRAIAL DO CABO',
      'BUZIOS',
      'CABO FRÍO',
      'FLORIANOPOLIS',
      'MACEIO',
      'MARAGOGI',
      'NATAL',
      'PORTO DE GALINHAS',
      'RECIFE',
      'RÍO DE JANEIRO',
      'SALVADOR DE BAHIA',
    ],
  },
  Chile: {
    docId: '1EM5RcqkEC9nYhtiiHZQ0nhoWie0omKIv1LJxZCwMvrg',
    tabs: ['SANTIAGO', 'PUERTO VARAS'],
  },
  Colombia: {
    docId: '18cXQy3IUdKCob2NWGfXvZZt71lyKhU5fXcI3a3nukJk',
    tabs: ['BOGOTÁ', 'CARTAGENA', 'MEDELLIN', 'SANTA MARTA', 'SAN ANDRÉS'],
  },
  Perú: {
    docId: '1rgccbmOuO6cLtRVRnGt2-xxefJe2WjR0HnhC2zSivBM',
    tabs: ['CUSCO', 'LIMA'],
  },
  México: {
    docId: '1htqL5Mf5Sb_KFLKckIqW5EmIvRdJLjiVc4doIRI0EjI',
    tabs: ['CANCÚN', 'COSTA MUJERES', 'PLAYA DEL CARMEN', 'RIVIERA MAYA'],
  },
  Aruba: {
    docId: '1sMW7jF5i6q5FMQGdyqNlOk4WEjKawUcyvn1XE81sEWM',
    tabs: ['ALL INCLUSIVE', 'CON DESAYUNO'],
  },
  Jamaica: {
    docId: '135NDK5vI4Yvhc5ysUcHLCx_HH_7OKSpjy6aTB4UcyMg',
    tabs: ['MONTEGO BAY', 'OCHO RÍOS', 'NEGRIL', 'OTROS'],
  },
  Cuba: {
    docId: '1gCNBdTdXAnoSd2tZphcnQ0eG8g7_gH41dHZu4-4KiSU',
    tabs: ['LA HABANA', 'VARADERO', 'CAYO SANTA MARÍA & ENSENACHOS'],
  },
  Curazao: {
    docId: '12i46oIMBM3e9BBdpGrGTiSPCvtvakWrvDqlHskPFHZY',
    tabs: ['ALL INCLUSIVE', 'CON DESAYUNO'],
  },
  'República Dominicana': {
    docId: '1_efABirFH3I6xsUCLhxHzC1RkEMlaTZ6e2y2bRdxjMA',
    tabs: ['PUNTA CANA', 'BAYAHIBE', 'SAMANÁ'],
  },
};

// Tab name → DB Ciudad nombre, for cases where they differ.
// Per-country overrides (country is matched via SHEET_SOURCES key).
const CITY_NAME_OVERRIDES: Record<string, Record<string, string>> = {
  Aruba: {
    'ALL INCLUSIVE': 'Aruba All Inclusive',
    'CON DESAYUNO': 'Aruba solo desayuno',
  },
  Curazao: {
    'ALL INCLUSIVE': 'Curazao All Inclusive',
    'CON DESAYUNO': 'Curazao solo desayuno',
  },
  Brasil: {
    'ALL INCLUSIVE BAHIA': 'All Inclusive en Bahía',
    'ALL INCLUSIVE EN ALAGOAS': 'All Inclusive en Alagoas',
    'SALVADOR DE BAHIA': 'Salvador de Bahía',
  },
  Portugal: {
    OPORTO: 'Porto', // alias: Oporto (client) = Porto (DB)
  },
  España: {
    'PALMA DE MALLORCA': 'Mallorca', // alias: Palma de Mallorca (client) = Mallorca (DB)
  },
};

// ---------------------------------------------------------------------------
// CSV parser — handles quoted fields with doubled-quote escaping.
// Google Sheets CSV output is well-formed so this minimal parser is enough.
// ---------------------------------------------------------------------------

function parseCSV(text: string): string[][] {
  const rows: string[][] = [];
  let row: string[] = [];
  let field = '';
  let inQuotes = false;

  for (let i = 0; i < text.length; i++) {
    const c = text[i];
    if (inQuotes) {
      if (c === '"') {
        if (text[i + 1] === '"') {
          field += '"';
          i++;
        } else {
          inQuotes = false;
        }
      } else {
        field += c;
      }
    } else {
      if (c === '"') {
        inQuotes = true;
      } else if (c === ',') {
        row.push(field);
        field = '';
      } else if (c === '\n') {
        row.push(field);
        rows.push(row);
        row = [];
        field = '';
      } else if (c === '\r') {
        // skip, handle on \n
      } else {
        field += c;
      }
    }
  }
  if (field.length > 0 || row.length > 0) {
    row.push(field);
    rows.push(row);
  }
  return rows;
}

// ---------------------------------------------------------------------------
// Normalisation helpers
// ---------------------------------------------------------------------------

function normalizeName(s: string): string {
  return s.trim().toLowerCase().replace(/\s+/g, ' ');
}

function normalizeForMatch(s: string): string {
  return s
    .normalize('NFD')
    .replace(/[̀-ͯ]/g, '')
    .toLowerCase()
    .replace(/\s+/g, ' ')
    .trim();
}

function parseCategoria(raw: string): {
  categoria: number | null;
  categoriaTexto: string | null;
} {
  const value = raw.trim();
  if (!value) return { categoria: null, categoriaTexto: null };
  if (value.toUpperCase() === 'CATEGORIA') return { categoria: null, categoriaTexto: null }; // junk header

  // Pure N* (e.g. "3*", "4*", "5*", "2*")
  const pure = /^([1-5])\s*\*$/.exec(value);
  if (pure) return { categoria: Number(pure[1]), categoriaTexto: null };

  // Hybrid e.g. "4*SUP", "3* - Básico", "3* - Super Básico"
  const hybrid = /^([1-5])\s*\*/.exec(value);
  if (hybrid) return { categoria: Number(hybrid[1]), categoriaTexto: value };

  // Pure text — "Básica", "Media", "Sup", "Superior", "Media Sup", etc.
  return { categoria: null, categoriaTexto: value };
}

// ---------------------------------------------------------------------------
// Parsed shapes
// ---------------------------------------------------------------------------

interface ParsedHotel {
  pais: string;
  tabName: string;       // original tab name from the sheet
  ciudadNombre: string;  // resolved city name after overrides (matches DB)
  nombre: string;
  categoria: number | null;
  categoriaTexto: string | null;
  comentarios: string | null;
  ubicacion: string | null;
  aclaracion: string | null;
}

interface ImportPlan {
  hotels: ParsedHotel[];
  perTab: Array<{ pais: string; tabName: string; ciudadNombre: string; count: number }>;
  discardedRows: number;
  duplicatesCollapsed: number;
  categoriaBreakdown: Record<string, number>;
  uniqueTextCategorias: Set<string>;
}

// ---------------------------------------------------------------------------
// Fetch + parse one tab
// ---------------------------------------------------------------------------

async function fetchTab(docId: string, tab: string): Promise<string[][]> {
  const url = `https://docs.google.com/spreadsheets/d/${docId}/gviz/tq?tqx=out:csv&sheet=${encodeURIComponent(tab)}`;
  const res = await fetch(url);
  if (!res.ok) throw new Error(`Failed to fetch ${tab} from ${docId}: HTTP ${res.status}`);
  const text = await res.text();
  return parseCSV(text);
}

function extractHotelsFromTab(
  rows: string[][],
  pais: string,
  tabName: string,
  ciudadNombre: string,
): { hotels: ParsedHotel[]; discarded: number } {
  // Find header row (contains "HOTEL")
  let headerIdx = -1;
  for (let i = 0; i < Math.min(rows.length, 10); i++) {
    if (rows[i]?.some((c) => (c ?? '').trim().toUpperCase() === 'HOTEL')) {
      headerIdx = i;
      break;
    }
  }
  if (headerIdx === -1) return { hotels: [], discarded: 0 };

  const header = rows[headerIdx].map((c) => (c ?? '').trim().toUpperCase());
  const idx = {
    HOTEL: header.indexOf('HOTEL'),
    CATEGORIA: header.indexOf('CATEGORIA'),
    COMENTARIOS: header.indexOf('COMENTARIOS'),
    UBICACION: header.indexOf('UBICACIÓN') === -1
      ? header.indexOf('UBICACION')
      : header.indexOf('UBICACIÓN'),
    ACLARACION: header.indexOf('ACLARACIÓN EXTRA') === -1
      ? header.indexOf('ACLARACION EXTRA')
      : header.indexOf('ACLARACIÓN EXTRA'),
  };

  const out: ParsedHotel[] = [];
  let discarded = 0;

  for (let i = headerIdx + 1; i < rows.length; i++) {
    const r = rows[i];
    const nameRaw = (r[idx.HOTEL] ?? '').trim();
    if (!nameRaw) continue;

    // Neighborhood markers (e.g. "PALERMO:") and section headers
    if (nameRaw.endsWith(':')) {
      discarded++;
      continue;
    }

    // City-section header inside a multi-city tab (e.g. "MENDOZA", "BARILOCHE"
    // inside the Argentina Buenos Aires tab). Heuristic: all-uppercase word(s),
    // no category, no comments.
    const categoriaRaw = (r[idx.CATEGORIA] ?? '').trim();
    const isAllCaps = nameRaw === nameRaw.toUpperCase() && /[A-ZÁÉÍÓÚÑ]/.test(nameRaw);
    const looksLikeSectionHeader =
      isAllCaps &&
      !categoriaRaw &&
      !/\d/.test(nameRaw) &&
      nameRaw.length > 3 &&
      nameRaw.length < 50;
    if (looksLikeSectionHeader) {
      discarded++;
      continue;
    }

    // Header duplicates — rows where col B is literally "CATEGORIA"
    if (categoriaRaw.toUpperCase() === 'CATEGORIA') {
      discarded++;
      continue;
    }

    // Strip trailing " 3*" / " 4*" etc. from name if present
    const cleanName = nameRaw.replace(/\s+[1-5]\*(?:SUP)?(?:\s*-\s*[A-Za-zÁÉÍÓÚáéíóúÑñ ]+)?\s*$/, '').trim();

    const { categoria, categoriaTexto } = parseCategoria(categoriaRaw);

    out.push({
      pais,
      tabName,
      ciudadNombre,
      nombre: cleanName,
      categoria,
      categoriaTexto,
      comentarios: idx.COMENTARIOS >= 0 ? (r[idx.COMENTARIOS] ?? '').trim() || null : null,
      ubicacion: idx.UBICACION >= 0 ? (r[idx.UBICACION] ?? '').trim() || null : null,
      aclaracion: idx.ACLARACION >= 0 ? (r[idx.ACLARACION] ?? '').trim() || null : null,
    });
  }

  return { hotels: out, discarded };
}

// ---------------------------------------------------------------------------
// Build import plan (fetch + parse + dedup, no DB writes)
// ---------------------------------------------------------------------------

export async function buildImportPlan(): Promise<ImportPlan> {
  const all: ParsedHotel[] = [];
  const perTab: ImportPlan['perTab'] = [];
  let totalDiscarded = 0;

  for (const [pais, src] of Object.entries(SHEET_SOURCES)) {
    for (const tab of src.tabs) {
      const override = CITY_NAME_OVERRIDES[pais]?.[tab];
      const ciudadNombre = override ?? tab;
      const rows = await fetchTab(src.docId, tab);
      const { hotels, discarded } = extractHotelsFromTab(rows, pais, tab, ciudadNombre);
      all.push(...hotels);
      totalDiscarded += discarded;
      perTab.push({ pais, tabName: tab, ciudadNombre, count: hotels.length });
    }
  }

  // Dedup by (normalizedName, ciudadNombre, pais)
  const seen = new Map<string, ParsedHotel>();
  let collapsed = 0;
  for (const h of all) {
    const key = `${h.pais}|${h.ciudadNombre}|${normalizeName(h.nombre)}`;
    if (seen.has(key)) collapsed++;
    seen.set(key, h); // last wins
  }
  const deduped = Array.from(seen.values());

  // Category histogram
  const categoriaBreakdown: Record<string, number> = {};
  const uniqueTextCategorias = new Set<string>();
  for (const h of deduped) {
    const label =
      h.categoria !== null && h.categoriaTexto === null
        ? `${h.categoria}*`
        : h.categoria !== null
        ? `${h.categoria}* (${h.categoriaTexto})`
        : h.categoriaTexto
        ? `text: ${h.categoriaTexto}`
        : '(empty)';
    categoriaBreakdown[label] = (categoriaBreakdown[label] ?? 0) + 1;
    if (h.categoria === null && h.categoriaTexto) uniqueTextCategorias.add(h.categoriaTexto);
  }

  return {
    hotels: deduped,
    perTab,
    discardedRows: totalDiscarded,
    duplicatesCollapsed: collapsed,
    categoriaBreakdown,
    uniqueTextCategorias,
  };
}

// ---------------------------------------------------------------------------
// Dry-run report
// ---------------------------------------------------------------------------

async function printReport(plan: ImportPlan): Promise<void> {
  console.log('='.repeat(70));
  console.log('HOTEL IMPORT — DRY RUN');
  console.log('='.repeat(70));
  console.log();
  console.log(`Total hotels (deduped): ${plan.hotels.length}`);
  console.log(`Tabs read: ${plan.perTab.length}`);
  console.log(`Rows discarded (section markers, header repeats, etc.): ${plan.discardedRows}`);
  console.log(`Duplicates collapsed within same ciudad: ${plan.duplicatesCollapsed}`);
  console.log();

  // Breakdown by country
  const byCountry: Record<string, number> = {};
  for (const h of plan.hotels) byCountry[h.pais] = (byCountry[h.pais] ?? 0) + 1;
  console.log('Per country:');
  for (const [p, n] of Object.entries(byCountry).sort((a, b) => b[1] - a[1])) {
    console.log(`  ${p.padEnd(25)} ${n}`);
  }
  console.log();

  // Per tab
  console.log('Per tab (top 15 by count):');
  for (const t of plan.perTab.sort((a, b) => b.count - a.count).slice(0, 15)) {
    const mark = t.tabName === t.ciudadNombre ? '' : ` → ${t.ciudadNombre}`;
    console.log(`  ${t.pais}/${t.tabName}${mark}: ${t.count}`);
  }
  console.log();

  // Categorias
  console.log('Categoría breakdown:');
  for (const [label, n] of Object.entries(plan.categoriaBreakdown).sort((a, b) => b[1] - a[1]).slice(0, 25)) {
    console.log(`  ${String(n).padStart(4)}  ${label}`);
  }
  if (plan.uniqueTextCategorias.size > 0) {
    console.log();
    console.log('Unique text categorías (will go to categoriaTexto):');
    for (const t of Array.from(plan.uniqueTextCategorias).sort()) {
      console.log(`  - ${t}`);
    }
  }
  console.log();

  // Check: países and cities from Sheet that don't exist in DB
  const dbPaises = await prisma.pais.findMany({
    select: { id: true, nombre: true },
  });
  const dbPaisByName = new Map(dbPaises.map((p) => [p.nombre, p.id]));
  const paisesMissing: string[] = [];
  const sheetPaises = new Set(plan.hotels.map((h) => h.pais));
  for (const p of sheetPaises) {
    if (!dbPaisByName.has(p)) paisesMissing.push(p);
  }

  const dbCiudades = await prisma.ciudad.findMany({
    select: { id: true, nombre: true, paisId: true, pais: { select: { nombre: true } } },
  });
  const dbByKey = new Map<string, string>();
  for (const c of dbCiudades) {
    if (!c.pais) continue;
    dbByKey.set(`${c.pais.nombre}|${normalizeForMatch(c.nombre)}`, c.id);
  }
  const missing: Array<{ pais: string; ciudadNombre: string }> = [];
  const seen = new Set<string>();
  for (const h of plan.hotels) {
    const key = `${h.pais}|${normalizeForMatch(h.ciudadNombre)}`;
    if (seen.has(key)) continue;
    seen.add(key);
    if (!dbByKey.has(key)) missing.push({ pais: h.pais, ciudadNombre: h.ciudadNombre });
  }

  if (paisesMissing.length > 0) {
    console.log(`⚠️  ${paisesMissing.length} países missing from DB — will be created on --confirm:`);
    for (const p of paisesMissing) console.log(`    - ${p}`);
    console.log();
  }
  if (missing.length === 0) {
    console.log('✅ All cities from Sheets already exist in DB.');
  } else {
    console.log(`⚠️  ${missing.length} cities missing from DB — will be created on --confirm:`);
    for (const m of missing) {
      const paisExists = dbPaisByName.has(m.pais) ? '' : ' (país missing too)';
      console.log(`    - ${m.pais} / ${m.ciudadNombre}${paisExists}`);
    }
  }
  console.log();
  console.log('='.repeat(70));
  console.log(`Run with --confirm to create these hotels in DB.`);
  console.log(`Note: this does NOT delete existing hotels. Wipe happens in migrate-hotels.ts.`);
  console.log('='.repeat(70));
}

// ---------------------------------------------------------------------------
// Persist: create missing ciudades + insert alojamiento rows
// ---------------------------------------------------------------------------

// Each sheet country maps to a region (for auto-creating missing países)
const COUNTRY_TO_REGION: Record<string, string> = {
  España: 'Europa',
  Italia: 'Europa',
  'Países Bajos': 'Europa',
  'Reino Unido': 'Europa',
  Francia: 'Europa',
  Portugal: 'Europa',
  'Estados Unidos': 'America del Norte',
  Argentina: 'Sudamerica',
  Brasil: 'Sudamerica',
  Chile: 'Sudamerica',
  Colombia: 'Sudamerica',
  Perú: 'Sudamerica',
  México: 'Caribe',
  Aruba: 'Caribe',
  Jamaica: 'Caribe',
  Cuba: 'Caribe',
  Curazao: 'Caribe',
  'República Dominicana': 'Caribe',
};

async function persist(plan: ImportPlan): Promise<void> {
  console.log('🔄 Persisting to DB…');

  // Load regions
  const regions = await prisma.region.findMany({ select: { id: true, nombre: true } });
  const regionIdByName = new Map(regions.map((r) => [r.nombre, r.id]));

  // Load paises by name
  let paises = await prisma.pais.findMany({ select: { id: true, nombre: true } });
  const paisIdByName = new Map(paises.map((p) => [p.nombre, p.id]));

  // Create missing países
  const sheetPaises = new Set(plan.hotels.map((h) => h.pais));
  let createdPaises = 0;
  for (const p of sheetPaises) {
    if (paisIdByName.has(p)) continue;
    const regionName = COUNTRY_TO_REGION[p];
    const regionId = regionName ? regionIdByName.get(regionName) : undefined;
    if (!regionId) {
      throw new Error(`Region not found for pais ${p} (expected "${regionName}")`);
    }
    const created = await prisma.pais.create({
      data: { brandId: BRAND_ID, nombre: p, regionId },
    });
    paisIdByName.set(p, created.id);
    createdPaises++;
  }
  if (createdPaises > 0) console.log(`   ✓ ${createdPaises} países creados`);

  // Load existing ciudades
  const dbCiudades = await prisma.ciudad.findMany({
    select: { id: true, nombre: true, paisId: true, pais: { select: { nombre: true } } },
  });
  const ciudadByKey = new Map<string, string>();
  for (const c of dbCiudades) {
    if (!c.pais) continue;
    ciudadByKey.set(`${c.pais.nombre}|${normalizeForMatch(c.nombre)}`, c.id);
  }

  // Create missing ciudades
  let createdCiudades = 0;
  const uniqueCities = new Set<string>();
  for (const h of plan.hotels) {
    const key = `${h.pais}|${normalizeForMatch(h.ciudadNombre)}`;
    if (uniqueCities.has(key)) continue;
    uniqueCities.add(key);
    if (ciudadByKey.has(key)) continue;

    const paisId = paisIdByName.get(h.pais);
    if (!paisId) {
      throw new Error(`País not found in DB: ${h.pais}`);
    }
    const created = await prisma.ciudad.create({
      data: { nombre: h.ciudadNombre, paisId },
    });
    ciudadByKey.set(key, created.id);
    createdCiudades++;
  }
  console.log(`   ✓ ${createdCiudades} ciudades creadas (las faltantes del Sheet)`);

  // Insert hotels
  let createdHotels = 0;
  for (const h of plan.hotels) {
    const ciudadId = ciudadByKey.get(`${h.pais}|${normalizeForMatch(h.ciudadNombre)}`);
    const paisId = paisIdByName.get(h.pais);
    if (!ciudadId || !paisId) {
      throw new Error(`Unresolved city/country for hotel: ${h.nombre} (${h.pais}/${h.ciudadNombre})`);
    }
    await prisma.alojamiento.create({
      data: {
        id: await generateSequentialId(prisma, 'alojamiento'),
        brandId: BRAND_ID,
        nombre: h.nombre,
        ciudadId,
        paisId,
        categoria: h.categoria,
        categoriaTexto: h.categoriaTexto,
        comentarios: h.comentarios,
        ubicacion: h.ubicacion,
        aclaracion: h.aclaracion,
      },
    });
    createdHotels++;
    if (createdHotels % 100 === 0) {
      console.log(`   … ${createdHotels} / ${plan.hotels.length}`);
    }
  }
  console.log(`   ✓ ${createdHotels} alojamientos creados`);
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

async function main() {
  const args = process.argv.slice(2);
  const confirm = args.includes('--confirm');
  const snapshotArg = args.find((a) => a.startsWith('--snapshot-output='));

  console.log('📖 Reading hotel sheets from client docs…');
  const plan = await buildImportPlan();

  if (snapshotArg) {
    const path = snapshotArg.split('=', 2)[1];
    writeFileSync(path, JSON.stringify(plan.hotels, null, 2));
    console.log(`   ✓ Snapshot written to ${path}`);
  }

  if (!confirm) {
    await printReport(plan);
    return;
  }

  await printReport(plan);
  console.log();
  console.log('⚠️  --confirm flag detected. Persisting to DB in 3 seconds…');
  await new Promise((r) => setTimeout(r, 3000));
  await persist(plan);
  console.log('✅ Done.');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
